### ISSUE TITLE
powershell and windows script produce different output

### ISSUE THREAD

**Issue by clegaard** [INTO-CPS-Association/FMI2-VDM-Model#9] opened 2020-03-11 10:42 UTC
It seems that running the powershell and bash script produces different output for valid model descriptions. This complicates things for other tools which relies on VDMCheck for validation.

On running the powershell script returns "true" 
``` powershell
.\VDMCheck2.ps1 -fmu modelDescription.xml
true
```
Running the bash returns "No errors found.
``` bash
./VDMCheck2.sh modelDescription.xml 
No errors found.
```

In the powershell script this can be fixed by:
``` powershell
$res = java -Xmx1g -cp "vdmj-4.3.0.jar;annotations-1.0.0.jar;annotations2-1.0.0.jar" com.fujitsu.vdmj.VDMJ -vdmsl -q -annotations -e "isValidFMIModelDescription($vdm_var)" model $vdm_file

...
if ($res -eq 'true') {
	return "No errors found."
}
else {
	return "Errors found."
}
```

**Comment by nickbattle** [comment] 2020-03-11 11:45
Ah yes, that's another place where the two scripts have diverged. As I said before, I've not been maintaining the Powershell script.

I'll make the change you suggest (though I can't test it).

**Comment by nickbattle** [comment] 2020-03-11 11:51
Just pushed Build 200311, Add text message result to Powershell script.

**Comment by clagms** [comment] 2020-03-15 05:29
Nick, perhaps we could move the extract functionality into Java?
Then people would call the jar.
There is the into CPS to library with had all the code you need to deal
with fmus.

Or is this not that big of a deal? If the interface of the script does not
change that much, keeping the two scripts should be a problem...

**Comment by nickbattle** [comment] 2020-03-15 08:48
@clagms Yes, that's probably a good idea. It is "easier" in bash, but if it's causing a lot of problems for people on different platforms, it would be simpler for everyone in Java.

I'll take a look. I already have Java code to unpack ZIP files (VDMJ can deal with specifications inside Microsoft .docx files, which are ZIPs) and the rest of it is pretty simple.

**Comment by clagms** [comment] 2020-03-15 10:00
This is the link to the intocps fmi library @nickbattle 
https://github.com/INTO-CPS-Association/org.intocps.maestro.fmi
This class: NativeLibraryLoader

**Comment by nickbattle** [comment] 2020-03-17 19:20
I've just pushed a new release that includes a top level VDMCheck class that should do the same as the bash or Powershell scripts.

`java -jar <path to installation>/fmi2vdm-0.0.2.jar <FMU file or XML file>`

Can people give this a try? If it's stable, I'll port it to the 0.0.3 (FMI3) tool.

**Comment by clegaard** [comment] 2020-03-18 07:13
Thank you Nick! I have tested it on Ubuntu 19, where it works perfectly. 

On another note would it be possible to add the option to pass the model description as a string? This would be very useful for tools which relies on VDMCheck for validation.

**Comment by nickbattle** [comment] 2020-03-18 08:53
LOL, oh yes I remember you mentioned that. I forgot to add the "-v" processing as well, so I'll see whether I can squeeze in string processing while I fix that.

Can  someone try on Windows? I'm sure Linux clones will work, but... you know what MS is like :-(

**Comment by nickbattle** [comment] 2020-03-18 15:13
OK, so I've added a -x flag, so that you can provide the XML directly. The usage line is now:
```
Usage: VDMCheck2.sh [-v <VDM outfile>] -x <XML> | <file>.fmu | <file>.xml
```
I've updated the bash script to have the same option. I can't maintain the PS script, so I've deleted it in this release, since Windows users can use the direct Java execution now anyway.

@clegaard If you could try this out and let me know? When it's looking OK, I'll update the FMI3 tools to match.

**Comment by nickbattle** [comment] 2020-03-18 15:15
PS. It expects a single command line option for the -x option. So if you were using bash command line, you would have to put the XML source in "double quotes".

**Comment by clegaard** [comment] 2020-03-18 17:51
I will try it out and get back to you. I will probably get around to it tomorrow morning :)

**Comment by clegaard** [comment] 2020-03-18 22:12
When invoked on windows:
``` bash
java -jar fmi2vdm-0.0.2.jar modelDescription.xml
Error: Could not find or load main class com.fujitsu.vdmj.VDMJ
```
I don't have any experience with java, but it seems the powershell script used to invoke it as:
``` powershell
$res = java -Xmx1g -cp "vdmj-4.3.0.jar;annotations-1.0.0.jar;annotations2-1.0.0.jar" com.fujitsu.vdmj.VDMJ -vdmsl -q -annotations -e "isValidFMIModelDescription($vdm_var)" model $vdm_file
```

**Comment by nickbattle** [comment] 2020-03-19 08:25
OK, thanks for testing it. Windows is always a pain :(

The main class in the fmi2vdm.jar invokes a new process to launch VDMJ. It will be passing the right command line options, but it almost certainly is in the wrong current working directory, which is why the classpath doesn't contain VDMJ.

In bash it is simple to find "where the script is located" and then cd there so that the VDMJ jars are local. But from Java you have to pull all sorts of tricks to find this (and evidently it isn't working).

Can you try one test: change directory into wherever you installed VDMCheck and then try it - or is that what you did anyway?

The Java method to locate the installation folder is:
```
	private static File getJarLocation()
	{
		File location = new File(VDMCheck.class.getProtectionDomain()
				.getCodeSource().getLocation().getPath().replaceAll("%20", " "));
		
		return location.getParentFile();
	}
```
Is there any way you could try running that in Java in Windows, perhaps as a small test class with just that method? The File returned should be the location of the VDMCheck class (ie. the jar) - or whatever your test class is called.

**Comment by nickbattle** [comment] 2020-03-19 08:36
This is the source of that Java, BTW:
https://stackoverflow.com/questions/320542/how-to-get-the-path-of-a-running-jar-file

There are a lot of other idea in there if we get stuck here. We need to be able to locate the installation because the VDMJ has to be able to find the VDM-SL model files in that location, even if it's not executed in a new process.

**Comment by nickbattle** [comment] 2020-03-20 09:00
@clegaard One other thing... the Java above has a nasty "replaceAll" because of spaces in the folder name. There is a better way to solve this, but can you tell me the full pathname of the location where you installed VDMCheck when it failed? It may be that there are other special characters in there, and that would cause the behaviour you see.

**Comment by clagms** [comment] 2020-03-20 12:12
@nickbattle I'm trying to figure this out, but to test my hypothesis I need to rebuild the jars.
I'm having trouble with that.
The readme files state that I just need to run mvn package...
When I try that in the FMI2_to_VDM folder, I get the following:
```
PS C:\srcctrl\IntoCPSAssociation\FMI-VDM-Model\FMI2_to_VDM> mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------------< fmi2:fmi2vdm >----------------------------
[INFO] Building fmi2vdm 0.0.2
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for fmi2:vdm-model:jar:0.0.2 is missing, no dependency information available
[WARNING] The POM for com.fujitsu:vdmj:jar:4.3.0 is missing, no dependency information available
[WARNING] The POM for com.fujitsu:annotations:jar:1.0.0 is missing, no dependency information available
[WARNING] The POM for com.fujitsu:annotations2:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.303 s
[INFO] Finished at: 2020-03-20T13:10:40+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fmi2vdm: Could not resolve dependencies for project fmi2:fmi2vdm:jar:0.0.2: The following artifacts could not be resolved: fmi2:vdm-model:jar:0.0.2, com.fujitsu:vdmj:jar:4.3.0, com.fujitsu:annotations:jar:1.0.0, com.fujitsu:annotations2:jar:1.0.0: Failure to find fmi2:vdm-model:jar:0.0.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

What am I doing wrong?

**Comment by nickbattle** [comment] 2020-03-20 12:40
Ah yes. It's saying that the Maven packages for the VDM-SL model and for VDMJ itself are not present in your repository. Those things are not *created* by this project, they are its dependencies.

So it's a mild pain... you need to get the projects for the FMI VDM-SL model, VDMJ and its annotations, and Maven install those first so that you have them in your local repo.

The VDM-SL model is https://github.com/INTO-CPS-Association/FMI-VDM-Model/tree/master/FMI2
The VDMJ tool is https://github.com/nickbattle/vdmj/tree/master/FJ-VDMJ4
The annotations are at https://github.com/nickbattle/vdmj/tree/master/Annotations and https://github.com/nickbattle/vdmj/tree/master/Annotations2

If you `mvn install` each of those first, the `mvn package` of VDMCheck should complete.

Sorry... this isn't as simple as I naively imagined :-(

**Comment by clagms** [comment] 2020-03-20 13:04
Thank you @nickbattle 
In the meantime, I think I got this to work by doing the following (for the record):
1. Create "lib" folder in the root of the repo, with the contents:
    - annotations-1.0.0.jar
    - annotations2-1.0.0.jar
    - vdmj-4.3.0.jar
2. Create the pom file [1] at the root of the repo.
3. Run the following, from the command line at the root of the repo:
```
mvn install:install-file -Dfile=".\lib\vdmj-4.3.0.jar" -DgroupId="com.fujitsu" -DartifactId="vdmj" -Dversion="4.3.0" -Dpackaging="jar"
mvn install:install-file -Dfile=".\lib\annotations-1.0.0.jar" -DgroupId="com.fujitsu" -DartifactId="annotations" -Dversion="1.0.0" -Dpackaging="jar"
mvn install:install-file -Dfile=".\lib\annotations2-1.0.0.jar" -DgroupId="com.fujitsu" -DartifactId="annotations2" -Dversion="1.0.0" -Dpackaging="jar"
```
4. Run `mvn package` from the root of the repo.



[1] Pom file contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
     http://maven.apache.org/xsd/maven-4.0.0.xsd">
     
  <modelVersion>4.0.0</modelVersion>

	<!-- parent pom -->
  <groupId>vmd</groupId>
  <artifactId>vmd_projects</artifactId>
  <packaging>pom</packaging>
	<version>1.0</version>

	<!-- sub modules -->
	<modules>
      <module>COSIM</module>
      <module>COSIM_to_VDM</module>
      <module>FMI2</module>
      <module>FMI2_to_VDM</module>
  </modules>
	
</project>
```

**Comment by nickbattle** [comment] 2020-03-20 13:12
@clagms Nice! You'll also need the package for the VDM model itself, vdm-model-0.0.2.jar.

**Comment by nickbattle** [comment] 2020-03-20 13:16
Actually, that might be quite useful to keep - could you check the POM into the top level?

**Comment by clagms** [comment] 2020-03-20 15:22
I will.. once I manage to solve this problem... it's personal now xD

**Comment by clagms** [comment] 2020-03-20 18:29
I think commit a0ac8df6a5b0a209e3459b26936bc50365894c2e fixes this issue @nickbattle .
Could you check that I did not break it on linux?
I took the wrong turn at the beginning, thinking that this might have been caused by the fact that the jar files were not in the main jar. That was not the problem.
The problem is in the -cp argument.
I used "./*" for the cp and it works.
I also tried a cleaner cp, such as "./vdmj-4.3.0.jar:..." but that did not work.

**Comment by nickbattle** [comment] 2020-03-20 19:08
This does work on Linux! So many thanks for the testing and fixes.

I'm a bit worried about the "./*" though. That would presumably pick up the fmi2vdm.jar as well as the VDMJ jars. That's harmless I suppose, but it's "wrong". It might also pick up the "model" folder as well as the jars (not that there is Java in there, but still...)

I wonder whether the problem is the ":" separators that Linux has on the classpath, compared to Window's ";" requirement - can you try the original classpath with the right class separator (File.pathSeparator)?

**Comment by clagms** [comment] 2020-03-20 19:34
I can try this Nick!

However, note that the wildcard isn't so bad: it avoids you having to remember to change the version of the jars, and it only includes the jars (so the "model" folder won't be picked up).

**Comment by clagms** [comment] 2020-03-20 19:41
Fixed this with 7ea5f82467593cfd73be9d051f7329f61eab91b9

**Comment by nickbattle** [comment] 2020-03-20 20:03
@clagms OK, that's *much* better, and I think we've found the original problem: I'd forgotten about Windows path separators... grrr... :-(

Anyway, I'll tidy up the %20 stuff in the location method and release this, both for VDMCheck2 and 3.  Thanks again for the help!

**Comment by clagms** [comment] 2020-03-21 07:08
Thank you Nick!

**Comment by clegaard** [comment] 2020-03-21 17:16
I have integrated the tool in my test suite, it appears to work as intended on both Windows and Linux now :)

**Comment by nickbattle** [comment] 2020-03-21 17:30
OK, that's great news @clegaard. I'll close the issue.

**Closed as completed by nickbattle** 2020-03-21 17:30 UTC
